[phases.setup]
  nixPkgs = ['python39', 'python39Packages.pip', 'gcc']

[phases.install]
  cmds = [
    'python -m venv /opt/venv',
    '/opt/venv/bin/pip install --no-cache-dir -r requirements.txt'
  ]

[phases.build]
  cmds = ['echo "No build step required"']

[start]
  cmd = '/opt/venv/bin/gunicorn -w 4 -b 0.0.0.0:$PORT affiliate_finder:app'

[environment]
  PYTHONUNBUFFERED = '1'
  PYTHONPATH = '/opt/venv/lib/python3.9/site-packages'