[phases.setup]
  nixPkgs = ['python39', 'gcc']
  aptPkgs = ['python3-pip']

[phases.install]
  cmds = ['python -m venv /opt/venv', '. /opt/venv/bin/activate', 'pip install -r requirements.txt']

[phases.build]
  cmds = ['echo "No build step required"']

[start]
  cmd = 'gunicorn -w 4 -b 0.0.0.0:$PORT affiliate_finder:app'